### ISSUE TITLE
Uploading speed is slow

### ISSUE THREAD

**Issue by wahib922** [gotev/android-upload-service#558] opened 2021-01-19 14:29 UTC
i am uploading images and videos on my server and my network upload speed is around 100mbps but the upload speed of my app is very slow 
IOS app upload speed is really fast on the same network like my app is uploading around 2mbps and ios is doing around 15mbps.

**Comment by gotev** [comment] 2021-01-19 22:30
That's interesting. Have you tried the same upload on multiple Android devices? Is the result the same?

If not already, use OkHttp stack which benefits from Okio and many other performance improvements (check the configuration wiki).

Tune also the Upload Buffer Size https://github.com/gotev/android-upload-service/wiki/Configuration#upload-buffer-size

By default it's set to 4KB. Try increasing it.

Let me know the results you get across different Android phones and different upload buffer size settings 😉

**Comment by gotev** [comment] 2021-01-24 17:09
@wahib922 any update on this?

**Comment by wahib922** [comment] 2021-01-24 17:18
@gotev i have been already using OKHttp stack.

but increasing the buffer size increased the upload speed.

i am also facing this issue 

Context.startForegroundService() did not then call Service.startForeground()

app got crashed sometimes but this happen randomly 
i have updated the library to latest version but that doesn't help.

**Comment by gotev** [comment] 2021-01-24 17:21
Thank you for the feedback👍. Closing this as the issue is resolved by increasing the buffer.

If you are having crashes or other issues, open a new issue with all the required details 😉

**Closed by gotev** 2021-01-24 17:21 UTC
