### ISSUE TITLE
For some device it works and for some not and i am using 4x version

### ISSUE THREAD

**Issue by pranayansaikia** [gotev/android-upload-service#503] opened 2020-05-22 16:44 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**OS and Lib versions (please complete the following information):**
- Android Upload Service version: [e.g. 4.3.0]
- Android version and API version: [e.g. Android 10]
- HTTP stack: [e.g. HurlStack or OkHttpStack]

**Request code:**
```kotlin
// the code you wrote to create the upload request
```
**Where have you added the request code?**
- [ ] Activity
- [ ] Service
- [ ] Other class (add additional info about it)

**Debug Log**:
```
// your debug log
```

**Comment by gotev** [comment] 2020-05-22 16:46
Unless you fill in the required information together with some evidence cases, there's no way to improve the library

**Comment by pranayansaikia** [comment] 2020-05-22 16:56
![pics](https://user-images.githubusercontent.com/22168449/82691271-3f971d80-9c7b-11ea-8660-da733364556e.jpeg)

**Comment by gotev** [comment] 2020-05-22 21:49
A demo project, a test case or ways to replicate your use cases will be useful. With only that issue title, this screenshot and no other detail, it's impossible to tell what the problem is. Please fill in the required information in the template.

**Comment by gotev** [comment] 2020-06-03 18:08
closing this for lack of relevant information

**Closed by gotev** 2020-06-03 18:08 UTC
