### ISSUE TITLE
Android crash when turning off WiFi during upload (using react-native-background-upload)

### ISSUE THREAD

**Issue by projuljustin** [gotev/android-upload-service#584] opened 2021-05-04 16:45 UTC
I understand, not the right github page. But I'm really really hoping you guys can help me.

**What do you want to achieve?**
Using react-native-background-upload to utilize android-upload-service for photo upload on react-native

**What have you tried to do?**
I've done extensive searching, and I did find an issue that mentioned this error. I don't fully understand how to resolve this in react-native and I'm desperate for help.

**Which Upload Service Version are you using?**
react-native-background-upload is currently using 4.3.0. I tried forking and changing that to 4.5.3 but it didn't seem to help.

**On which Android version?**
Android 10

**Additional info**
I am using product flavors to support dev, test and production builds. But I have had no issues with it since implementation. This is the only issue I've ever had with uploading and I would hate to abandon react-native-background-upload because of this, it's been great so far. It's unfortunate that it isn't being maintained, I hope someone will come along and take over. 

Error:
2021-05-03 15:06:30.092 11885-11885/? E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.myapp.webview, PID: 11885
java.lang.RuntimeException: Unable to create service net.gotev.uploadservice.UploadService: java.lang.IllegalArgumentException: You have to set namespace to your app package name (context.packageName) in your Application subclass
at android.app.ActivityThread.handleCreateService(ActivityThread.java:4180)
at android.app.ActivityThread.access$1600(ActivityThread.java:232)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2033)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:241)
at android.app.ActivityThread.main(ActivityThread.java:7617)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
Caused by: java.lang.IllegalArgumentException: You have to set namespace to your app package name (context.packageName) in your Application subclass
at net.gotev.uploadservice.UploadServiceConfig.getNamespace(UploadServiceConfig.kt:74)
at net.gotev.uploadservice.UploadServiceConfig.getBroadcastNotificationAction(UploadServiceConfig.kt:234)
at net.gotev.uploadservice.UploadServiceConfig.getBroadcastNotificationActionIntentFilter(UploadServiceConfig.kt:248)
at net.gotev.uploadservice.observer.request.NotificationActionsObserver.register(NotificationActionsObserver.kt:31)
at net.gotev.uploadservice.UploadService.onCreate(UploadService.kt:194)
at android.app.ActivityThread.handleCreateService(ActivityThread.java:4168)
at android.app.ActivityThread.access$1600(ActivityThread.java:232) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2033) 
at android.os.Handler.dispatchMessage(Handler.java:107) 
at android.os.Looper.loop(Looper.java:241) 
at android.app.ActivityThread.main(ActivityThread.java:7617) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941) 

I don't seem to get this issue when running my dev or tst app (com.myapp.webviewdev or com.myapp.webviewtest)

![image](https://user-images.githubusercontent.com/58796652/117039188-b9c28580-acc5-11eb-9f77-9b7bb31bd3e8.png)

**Comment by gotev** [comment] 2021-05-05 06:01
Hi!
From the stack trace you posted I can exclude Android Upload Service from the equation. This reply may be an useful insight: https://github.com/gotev/android-upload-service/issues/580#issuecomment-831192448

Other than that, there's nothing more I could do. I've seen you opened an issue also on the wrapper library. The problem is in how you are using the wrapper or in the wrapper itself. Closing this for now. If there's an evidence proving it's a library bug, please open a new issue with the details.

**Comment by gotev** [comment] 2021-05-05 06:03
Related wrapper library issue: https://github.com/Vydia/react-native-background-upload/issues/251

**Closed** 2021-05-05 06:03 UTC
Labels: support
