### ISSUE TITLE
crash app on android 8

### ISSUE THREAD

**Issue by rasoulinejad** [gotev/android-upload-service#381] opened 2018-03-25 10:01 UTC
java.lang.IllegalArgumentException: Android Oreo requires a notification configuration for the service to run. https://developer.android.com/reference/android/content/Context.html#startForegroundService(android.content.Intent)
at net.gotev.uploadservice.UploadRequest.startUpload(SourceFile:72)

**Comment by gotev** [comment] 2018-03-25 10:06
Check existing closed issues before opening a new one :smiley: 

Duplicate of #369

**Closed by gotev** 2018-03-25 10:06 UTC
