### ISSUE TITLE
onCompleted is not called

### ISSUE THREAD

**Issue by andsh** [gotev/android-upload-service#177] opened 2016-08-19 16:33 UTC
* Android Upload Service version (e.g. 3.0.3):
* Android version and API version (e.g. 6.0.1 API 23):

I expect the onCompleted callback to be called when the upload is finished
But it's not called

This is my request code:
```java
final String uploadId =
             new net.gotev.uploadservice.MultipartUploadRequest(getApplicationContext(), "https://www.motolife.bg/post_avatar.php")
             .addFileToUpload(filename, "photo")
             .addParameter("parameter","value")
             .setDelegate(new net.gotev.uploadservice.UploadStatusDelegate() {
               @Override
               public void onProgress(net.gotev.uploadservice.UploadInfo uploadInfo) {
                 Log.e("gotev","onProgress eltstr="+uploadInfo.getElapsedTimeString()+" elt="+uploadInfo.getElapsedTime()+" ratestr="+
                 uploadInfo.getUploadRateString()+" prc="+uploadInfo.getProgressPercent()+" tb="+uploadInfo.getTotalBytes()+" ub="+uploadInfo.getUploadedBytes());
               }
               @Override
               public void onError(net.gotev.uploadservice.UploadInfo uploadInfo, Exception e) {
                 Log.e("gotev","onError "+e.getMessage() + e.getStackTrace());
               }
               @Override
               public void onCompleted(net.gotev.uploadservice.UploadInfo uploadInfo, net.gotev.uploadservice.ServerResponse serverResponse) {
                 Log.e("gotev","onCompleted "+serverResponse.getHttpCode()+" "+serverResponse.getBodyAsString());
               }
               @Override
               public void onCancelled(net.gotev.uploadservice.UploadInfo uploadInfo) {
                 Log.e("gotev","onCancelled "+uploadInfo);
               }
             }).startUpload();
```
This is my library initialization code
```java
net.gotev.uploadservice.UploadService.NAMESPACE = bg.motolife.app.BuildConfig.APPLICATION_ID;
```
And this is my logcat output
```
08-19 19:31:21.649 1706-1706/bg.motolife.app E/gotev: uploadId=7e9235a9-de5a-4ead-8e2f-93ca25f30b20
08-19 19:31:21.938 1706-1706/bg.motolife.app E/gotev: onProgress eltstr=0s elt=248 ratestr=0 bit/s prc=0 tb=174870 ub=103
                                                      {"st":0}
```

The request is successfully received by the server. But there is now output from the onCompleted callback

**Comment by gotev** [comment] 2016-08-20 05:36
Is the request code added inside an Activity?
Is the Activity running when the Upload is complete?

**Comment by andsh** [comment] 2016-08-20 08:43
This request is in an activity
The activity is active during whole time since the start till the end of the request
The additional POST parameter is needed by me because I have to identify the uploaded file on the server according to the parameter's value

The only way to get onCompleted called is to use the different configuration - instead of this anonymous class i have made my activity class implements UploadStatusDelegateq added 4 Overriden methods to my activity: onProgress, onError, onCompleted,onCancelled
This way I see get the call to onCompleted method and can get the server response there.

But in the serverResponse i have another question.
On my server I send this response (PHP): echo json_encode(array("st"=>0));
On the onCompleted method of my activity in receive this string '{"st":0}' But in the beginning of this dtring i receive two additional bytes - 0xD and 0xA
What is the source of these two bytes in the beginning of my onCompleted.serverResponse?

**Comment by gotev** [comment] 2016-08-20 08:57
The reason why the anonymous class `onCompleted` method was not called is because it went out of scope. When you implement the interface in the activity, and the activity stays in the foreground till the end on of the operation, `onCompleted` gets called. It's just a matter of scopes, so it's not a bug in the library.

Regarding your server side, be sure that the response is in UTF 8 which is the default encoding the library uses. You can also get the raw response body bytes from the serverResponse object.

**Comment by andsh** [comment] 2016-08-20 09:19
To ensure the server response encoding I've modified the PHP script the following way:
header('Content-Type: application/json; charset=utf-8');
echo utf8_encode(json_encode(array("st"=>0)));

On the client side in the onCompleted method I inserted the following code
      int code = serverResponse.getHttpCode();
      Log.e("gotev", "onCompleted3 " + code);
      byte[] ba = serverResponse.getBody();
      for (int j=0; j<ba.length; j++) {
        Log.e("byte",String.format("%02X ", ba[j]));
      }
      String str2 = new String(ba, Charset.forName("UTF8"));
      Log.e("gotev", "strs equ= " + resps.equals(str2));
      JSONObject jo = new JSONObject(resps);
      int st = jo.getInt("st");
      Log.e("gotev", "onCompleted5 st=" + st);

And I've got the following in the Logcat in my Android Studio
08-20 12:13:50.999 20111-20111/bg.motolife.app E/gotev: onCompleted3 200
                                                        {"st":0}
08-20 12:13:51.000 20111-20111/bg.motolife.app E/byte: 0D 
08-20 12:13:51.000 20111-20111/bg.motolife.app E/byte: 0A 
08-20 12:13:51.000 20111-20111/bg.motolife.app E/byte: 7B 
08-20 12:13:51.000 20111-20111/bg.motolife.app E/byte: 22 
08-20 12:13:51.000 20111-20111/bg.motolife.app E/byte: 73 
08-20 12:13:51.000 20111-20111/bg.motolife.app E/byte: 74 
08-20 12:13:51.000 20111-20111/bg.motolife.app E/byte: 22 
08-20 12:13:51.000 20111-20111/bg.motolife.app E/byte: 3A 
08-20 12:13:51.000 20111-20111/bg.motolife.app E/byte: 30 
08-20 12:13:51.000 20111-20111/bg.motolife.app E/byte: 7D 
08-20 12:13:51.000 20111-20111/bg.motolife.app E/gotev: strs equ= true
08-20 12:13:51.001 20111-20111/bg.motolife.app E/gotev: onCompleted5 st=0

See, in the second string i don't see any string header because of new line and carriage return characters in the string
And then In the byte loop we see first 2 bytes are exactly line_feed and carriage_return

From where are these two bytes in the beginning of the serverResponse?

**Closed** 2016-08-20 09:18 UTC
Labels: support

**Comment by gotev** [comment] 2016-08-20 09:54
Updated the [Monitoring upload status](https://github.com/gotev/android-upload-service/wiki/Monitoring%20upload%20status) wiki page:

> The recommended way to use delegates inside Activities or Services is to implement the `UploadStatusDelegate` interface in your Activities or Services instead of using the anonymous inner class, to prevent variable out of scope problems.

Please make use of [markdown syntax to improve readability](https://github.com/gotev/android-upload-service/wiki/Asking-for-help#readability) the next time, as I've noted in the asking for help wiki page. I've done that for you this time in your posts.

Made some tests using the node.js demo server and the demo app provided in the examples, and this is what I get in the LogCat:
```shell
I/UploadServiceDemo: ID 27a37309-dde3-47cf-8f89-cc223d4fb767: completed in 0s at 0,00 Kbit/s. Response code: 200, body:[Upload Ok!]
E/UploadServiceDemo: Success:/storage/emulated/0/Download/11700901_10204551472013917_5124724800122680120_o.jpg
I/Header: Connection: close
I/Header: Date: Sat, 20 Aug 2016 09:48:04 GMT
I/Header: transfer-encoding: 
I/Header: X-Android-Received-Millis: 1471686484540
I/Header: X-Android-Response-Source: NETWORK 200
I/Header: X-Android-Selected-Protocol: http/1.1
I/Header: X-Android-Sent-Millis: 1471686484410
I/Header: X-Powered-By: Express
E/UploadServiceDemo: Printing response body bytes
E/UploadServiceDemo: 55 
E/UploadServiceDemo: 70 
E/UploadServiceDemo: 6C 
E/UploadServiceDemo: 6F 
E/UploadServiceDemo: 61 
E/UploadServiceDemo: 64 
E/UploadServiceDemo: 20 
E/UploadServiceDemo: 4F 
E/UploadServiceDemo: 6B 
E/UploadServiceDemo: 21 
```
So those CR and LF characters are added by your PHP server-side script in the response.
