### ISSUE TITLE
Wrong total files on FTP upload

### ISSUE THREAD

**Issue by hendrawd** [gotev/android-upload-service#183] opened 2016-08-31 03:58 UTC
From the example of UploadNotificationConfig:
`uploadNotificationConfig.setInProgressMessage("Uploaded [[UPLOADED_FILES]] of [[TOTAL_FILES]] at [[UPLOAD_RATE]] - [[PROGRESS]]")`

I think it is wrong behaviour that [[TOTAL_FILES]] decrease along with the successful upload increase.

Example while uploading 12 files: 
Uploaded 3 of 9 at 22Mbit/s - 25%
Uploaded 4 of 8 at 22Mbit/s - 33%
Uploaded 6 of 6 at 22Mbit/s - 50%

If that behaviour is intended to do, why not use [[REMAINING_FILES]] instead?

**Comment by gotev** [comment] 2016-08-31 04:58
You're right, that's an issue! The problem is that in FTP Upload the files gets removed from the files to upload and set into successfully uploaded files after completion, as you can see [here](https://github.com/gotev/android-upload-service/blob/master/uploadservice-ftp/src/main/java/net/gotev/uploadservice/ftp/FTPUploadTask.java#L104). I'm going to address that.

**Comment by gotev** [comment] 2016-08-31 05:08
@hendrawd the issue should be resolved after my commit. If you can, checkout the project, make some tests with the demo app and let me know. If the problem is fixed, it will be available in the upcoming 3.1 release.

**Comment by hendrawd** [comment] 2016-08-31 05:16
@gotev yes, i will

**Comment by gotev** [comment] 2016-09-11 09:59
@hendrawd can you confirm that this issue is resolved after the fix was committed?

**Comment by hendrawd** [comment] 2016-09-16 02:48
@gotev sorry i was on vacation last week, i will test it and let you know

**Comment by hendrawd** [comment] 2016-09-19 08:11
@gotev i have tested on the sample project and it's now working fine

**Comment by gotev** [comment] 2016-09-19 09:34
@hendrawd thank you for testing. I'm closing this

**Closed by gotev** 2016-09-19 09:34 UTC
Labels: bug
