### ISSUE TITLE
How do I show upload progress inside the application?

### ISSUE THREAD

**Issue by Aravindraj93** [gotev/android-upload-service#481] opened 2019-12-20 10:58 UTC
I have implemented the FTP file upload in my application and it works great. Thanks for this library. 
Can you help me to show the upload progress inside the application? And also if I have a list of files need to uploaded, how do I update it one by one?

**Comment by gotev** [comment] 2019-12-20 19:00
With 4.0 you can achieve what you need with a RequestObserver. In the demo app there's one declared globally at App level. You decide to which scope to register it (application, activity, fragment) depending on your UX and use cases.

**Comment by Aravindraj93** [comment] 2019-12-23 12:36
Thank you. I tried it but I get the following error while try to upload the second file once the first file upload gets completed. 
`java.lang.NullPointerException: Attempt to invoke virtual method 'boolean utils.IPAddressAndHostnameValidator.isValidIPorHostname(java.lang.String)' on a null object reference`

**Comment by gotev** [comment] 2019-12-23 13:59
Post here your full request code

**Comment by Aravindraj93** [comment] 2019-12-24 07:01
This is how I update the upload progress in recyclerview. 
`@Override
    public void onCompleted(@NotNull Context context, @NotNull UploadInfo uploadInfo) {
        Log.e("RECEIVER", "Completed: $uploadInfo");
        if (myfiles < MyfilePaths.size()){
            onDone(myfiles+1);
        }
    }

    @Override
    public void onCompletedWhileNotObserving() {
        Log.e("RECEIVER", "Completed while not observing");
    }

    @Override
    public void onError(@NotNull Context context, @NotNull UploadInfo uploadInfo, @NotNull Throwable throwable) {

    }

    @Override
    public void onProgress(@NotNull Context context, @NotNull UploadInfo uploadInfo) {
        Log.e("RECEIVER", "Progress: UploadID " + uploadInfo.getUploadId());
        Log.e("RECEIVER", "Progress: $uploadInfo " + uploadInfo.getSuccessfullyUploadedFiles());
        long uploadedBytes = uploadInfo.getUploadedBytes();
        long totalBytes = uploadInfo.getTotalBytes();
        String FileName = MyfilePaths.get(0).getFileName();
        FilesClass filesClass = new FilesClass(FileName, (float) uploadedBytes * 100 / totalBytes);
        fileListAdapter.updateProgress(filesClass, myfiles);

    }'

And this is how I upload file. 

` public void onDone(int myfile) {
        if (!ipAddressAndHostnameValidator.isValidIPorHostname(serverUrl)) {
            Toast.makeText(thisActivity, "Host Error", Toast.LENGTH_SHORT).show();
            return;
        }
        int ftpPort;
        try {
            ftpPort = Integer.parseInt(serverPort, 10);
        } catch (Exception exc) {
            Toast.makeText(thisActivity, "Port Error", Toast.LENGTH_SHORT).show();
            return;
        }

        if (MyfilePaths != null && myfiles < MyfilePaths.size()) {

            try {
                    myfiles = myfile;

                    myFile = new File(MyfilePaths.get(myfiles).getFileName());

                    String extension = myFile.getAbsolutePath().substring(myFile.getAbsolutePath().lastIndexOf("."));
                    Date date2 = new Date();
                    DateFormat sdf = new java.text.SimpleDateFormat("dd-MM-yyyy_hh-mm-ss-SSS");
                    String time = DateUtils.formatDateTime(thisActivity, date2.getTime(), DateUtils.FORMAT_SHOW_TIME);
                    String strDate = sdf.format(date2);


                    String channelname = SharedHelper.getKey(thisActivity, "ChannelID");

                    final FTPUploadRequest request = new FTPUploadRequest(this, serverUrl, ftpPort)
                            .setMaxRetries(MAX_RETRIES)
                            .setNotificationConfig((context, uploadId) -> getNotificationConfig(uploadId, R.string.ftp_upload))
                            .setUsernameAndPassword(ftpUsername, ftpPassword)
                            .setCreatedDirectoriesPermissions(new UnixPermissions("777"))
                            .setSocketTimeout(5000)
                            .setConnectTimeout(5000);

                    try {

                        request.addFileToUpload(String.valueOf(myFile), channelname + "/" + userID + "/" + userID + "_" + strDate + extension);

                    } catch (IOException exc) {
                        Toast.makeText(thisActivity,
                                getString(R.string.file_not_found, myFile),
                                Toast.LENGTH_LONG).show();
                    }
                    request.startUpload();

                    Toast.makeText(this, "Uploading...", Toast.LENGTH_LONG).show();

                } catch(Exception exc){
                    Toast.makeText(this, exc.getMessage(), Toast.LENGTH_LONG).show();
                }
            } else{
                Toast.makeText(thisActivity, "Empty List!!", Toast.LENGTH_SHORT).show();
            }
    }`

When I try to upload second file from onCompleted method all the values become NULL

**Comment by gotev** [comment] 2019-12-24 07:59
From what I see you have a state management problem.

```
ipAddressAndHostnameValidator.isValidIPorHostname(serverUrl)
```
Which causes the crash is not part of Android Upload Service and from what I see the problem you are encountering is not caused by a library bug. Since this is an issue tracker, there's nothing more I can do unless I have a clear bug evidence which can be reproduced.

```
When I try to upload second file from onCompleted method all the values become NULL
```
Double check your code. `ipAddressAndHostnameValidator` becomes null so either something is setting it to null or it's not property initialized. Recycler View updates are up to you. The only advice I can tell you is to always use immutable state (which is made easier if you use Kotlin).

Have a nice holiday and Christmas!

**Comment by Aravindraj93** [comment] 2019-12-24 08:05
Thank you so much for your advice. I really appreciate your time. Thank you once again.

**Comment by Aravindraj93** [comment] 2019-12-24 10:35
Just now I checked and I see that if I use non static variables inside the RequestObserverDelegate Override methods it shows null object reference 

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.live.lcam.stream.reporterlite, PID: 21348
    java.lang.NullPointerException: Attempt to invoke virtual method 'void adapter.FileListAdapter.updateProgress(helper.FilesClass, int)' on a null object reference
        at com.live.lcam.stream.reporterlite.MainActivity.onProgress(MainActivity.java:1005)
        at net.gotev.uploadservice.observer.request.RequestObserver.onReceive(RequestObserver.kt:41)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)`

If I declare fileListAdapter and MyfilePaths as non static variables, it shows null object reference inside the onProgress function. 

`@Override
    public void onCompleted(@NotNull Context context, @NotNull UploadInfo uploadInfo) {
        Log.e("RECEIVER", "Completed: $uploadInfo");
        if (myfiles < MyfilePaths.size()){
            onDone(myfiles+1);
        }
    }
    @Override
    public void onCompletedWhileNotObserving() {
        Log.e("RECEIVER", "Completed while not observing");
    }

    @Override
    public void onError(@NotNull Context context, @NotNull UploadInfo uploadInfo, @NotNull Throwable throwable) {

    }

    @Override
    public void onProgress(@NotNull Context context, @NotNull UploadInfo uploadInfo) {
        Log.e("RECEIVER", "Progress: UploadID " + uploadInfo.getUploadId());
        Log.e("RECEIVER", "Progress: $uploadInfo " + uploadInfo.getSuccessfullyUploadedFiles());
        long uploadedBytes = uploadInfo.getUploadedBytes();
        long totalBytes = uploadInfo.getTotalBytes();
        String FileName = MyfilePaths.get(0).getFileName();
        FilesClass filesClass = new FilesClass(FileName, (float) uploadedBytes * 100 / totalBytes);
        fileListAdapter.updateProgress(filesClass, myfiles);

    }`

**Comment by gotev** [comment] 2019-12-27 10:59
Closing this as it's not a library issue

**Closed by gotev** 2019-12-27 10:59 UTC

**Comment by Aravindraj93** [comment] 2019-12-27 11:05
Thank you for helping me on this issue. I couldn't solve this issue as it throws null object reference error. 
I do have a request or suggestion. Please add an example of showing upload progress inside the activity .  Thank you. @gotev
