### ISSUE TITLE
In Multipart upload, successful file upload count not increasing in OnProgress

### ISSUE THREAD

**Issue by svkdvlp** [gotev/android-upload-service#326] opened 2017-10-20 07:08 UTC
### What did you expect?

I want to upload multiple files in one request.

In UploadServiceBroadcastReceiver onProgress, "uploadInfo.getSuccessfullyUploadedFiles().size()" should increase after each file upload.

### What happened instead?

in onProgress, I  get always "uploadInfo.getSuccessfullyUploadedFiles().size()" value is 0.

in onCompleted I get totalfilescount in "uploadInfo.getSuccessfullyUploadedFiles().size()".

### Version info
* Android Upload Service version: 3.4
* Android version and API version: 23
* HTTP stack (e.g. HurlStack or OkHttpStack): OkHTTP

// your LogCat output here
10-20 11:53:49.094 16599-16599/com.example.web112.myapplication I/!--uploadProgress: Uploaded 0/2 0%
10-20 11:53:49.276 16599-17146/com.example.web112.myapplication D/UploadService: UploadTask - Broadcasting upload progress for d0211dc3-733a-42e2-83fa-35f8d6093683: 405949 bytes of 893659
10-20 11:53:49.278 16599-16599/com.example.web112.myapplication I/!--uploadProgress: Uploaded 0/2 45%
10-20 11:53:49.811 16599-17146/com.example.web112.myapplication D/UploadService: HttpUploadTask - Server responded with HTTP 200 to upload with ID: d0211dc3-733a-42e2-83fa-35f8d6093683
10-20 11:53:49.812 16599-17146/com.example.web112.myapplication D/UploadService: UploadTask - Broadcasting upload completed for d0211dc3-733a-42e2-83fa-35f8d6093683
10-20 11:53:49.870 16599-16599/com.example.web112.myapplication W/!--uploadCompleted: Uploaded 2/2

**Comment by gotev** [comment] 2017-10-20 07:39
Closing as it's duplicate of #180

**Closed by gotev** 2017-10-20 07:39 UTC
