### ISSUE TITLE
Error while uploading files to server

### ISSUE THREAD

**Issue by AhmadullahSaikat** [gotev/android-upload-service#325] opened 2017-10-16 16:58 UTC
I'm using latest version: 3.4

Here are my code:

    new BinaryUploadRequest(context, User.ADD_COMPANY)

            .addHeader(Constants.XREQUESTED_HEADER_KEY, Constants.XREQUESTED_HEADER_VALUE)

            .addParameter(User.TITLE, etOrganizationTitle.getText().toString())

            .addParameter(User.IMAGE, new File(imageFilePath)) // upload file to server

            .setNotificationConfig(new UploadNotificationConfig())

            .setMaxRetries(2)

            .startUpload();

My Server Json format is like that:

    {
      "name": "(Add) Company",
      "request": {
        "url": "my_url",
        "method": "POST",
        "header": [
          {
            "key": "X-Requested-With",
            "value": "XMLHttpRequest",
            "description": ""
          }
        ],
        "body": {
          "mode": "formdata",
          "formdata": [
            {
              "key": "title",
              "value": "TOSSL",
              "description": "",
              "type": "text"
            },
            {
              "key": "image",
              "value": "",
              "description": "",
              "type": "file"
            }
          ]
        }
      },
      "response": []
    }

I want to upload image (as file) to server...
Please help...

**Comment by gotev** [comment] 2017-10-17 16:31
From what I see there are some misconceptions in the code you posted.

Please refer to the wiki recipes page and the provided demo server for a good example of binary upload. I also encourage you to test your server with the provided demo app. Binary upload puts the binary content of the file as the body of the upload stream. Since this issue is not a bug or feature request, I'm going to close it.

**Closed by gotev** 2017-10-17 16:31 UTC
