### ISSUE TITLE
FTPUploadRequest stop in middle

### ISSUE THREAD

**Issue by shweps** [gotev/android-upload-service#287] opened 2017-07-06 10:54 UTC
Be sure to check [Asking for help](https://github.com/gotev/android-upload-service/wiki/Asking%20for%20help) page on the Wiki before opening a new issue! Delete this text when you create a new issue.

### Version info
* Android Upload Service version: uploadservice-ftp:3.2.4
* Android version and API version: lg g6, 7.0

### What did you expect?
full transfer of 3.8GB movie.

### What happened instead?
after 300MB +/- the transfer stop

### Library initialization code:
```java
// the code you wrote in your Application subclass here
```

### Request code:
 String uploadId =
                    new FTPUploadRequest(getContext(), "192.168.49.245", 1234)
                            .setUsernameAndPassword("ftp", "ftp")
                            .addFileToUpload(srcFilePath, desFileName)
                            .setNotificationConfig(new UploadNotificationConfig())
                            .setMaxRetries(4)
                            .startUpload();
#### Where have you added the request code?
Fragment

### LogCat output (please [set log level to DEBUG](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) first)
```
// your LogCat output here
```

### Server side
Which server did you use (e.g. node.js demo server provided in the examples, php script provided in the examples, own implementation)?
own implementation, well know server how work very good with ather metods

**Comment by gotev** [comment] 2017-07-06 11:55
Please enable debug log and post it here

**Comment by shweps** [comment] 2017-07-06 12:15
07-06 08:14:14.768 26593-26894/cmc.com.httpclient E/UploadRequest: null or empty upload ID. Generating it
07-06 08:14:14.769 26593-26894/cmc.com.httpclient E/UploadRequest: Created new upload request to 192.168.49.245 with ID: af4168fe-2c2b-48f8-bfc3-fc4bdec2129a
07-06 08:14:14.789 26593-26894/cmc.com.httpclient E/UploadRequest: null or empty upload ID. Generating it
07-06 08:14:14.789 26593-26894/cmc.com.httpclient E/UploadRequest: Created new upload request to 192.168.49.245 with ID: 4aa50051-069b-4f96-904c-e98f1dc1e0d1
07-06 08:14:14.798 26593-26593/cmc.com.httpclient E/UploadService: Successfully created new task with class: net.gotev.uploadservice.ftp.FTPUploadTask
07-06 08:14:14.800 26593-26593/cmc.com.httpclient E/UploadService: Successfully created new task with class: net.gotev.uploadservice.ftp.FTPUploadTask
07-06 08:14:14.800 26593-26899/cmc.com.httpclient E/UploadService: af4168fe-2c2b-48f8-bfc3-fc4bdec2129a now holds the foreground notification
07-06 08:14:14.828 26593-26899/cmc.com.httpclient E/FTPUploadTask: Connect timeout set to 15000ms
07-06 08:14:14.828 26593-26899/cmc.com.httpclient E/FTPUploadTask: Connecting to 192.168.49.245:1234 as ftp
07-06 08:14:14.829 26593-26900/cmc.com.httpclient E/FTPUploadTask: Connect timeout set to 15000ms
07-06 08:14:14.830 26593-26900/cmc.com.httpclient E/FTPUploadTask: Connecting to 192.168.49.245:1234 as ftp
07-06 08:14:15.092 26593-26899/cmc.com.httpclient E/FTPUploadTask: Socket timeout set to 30000ms. Enabled control keep alive every 15s
07-06 08:14:15.093 26593-26900/cmc.com.httpclient E/FTPUploadTask: Socket timeout set to 30000ms. Enabled control keep alive every 15s
07-06 08:14:15.124 26593-26900/cmc.com.httpclient E/FTPUploadTask: FTP default working directory is: /
07-06 08:14:15.126 26593-26900/cmc.com.httpclient E/FTPUploadTask: Starting FTP upload of: VID_20170308_163550.mp4 to: VID_20170308_163550.mp4
07-06 08:14:15.124 26593-26899/cmc.com.httpclient E/FTPUploadTask: FTP default working directory is: /
07-06 08:14:15.127 26593-26899/cmc.com.httpclient E/FTPUploadTask: Starting FTP upload of: Thumbs.db to: Thumbs.db
07-06 08:14:15.174 26593-26899/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for af4168fe-2c2b-48f8-bfc3-fc4bdec2129a: 4096 bytes of 13312
07-06 08:14:15.230 26593-26899/cmc.com.httpclient E/UploadTask: Broadcasting upload completed for af4168fe-2c2b-48f8-bfc3-fc4bdec2129a
07-06 08:14:15.239 26593-26899/cmc.com.httpclient E/UploadService: af4168fe-2c2b-48f8-bfc3-fc4bdec2129a now un-holded the foreground notification
07-06 08:14:15.239 26593-26899/cmc.com.httpclient E/FTPUploadTask: Logout and disconnect from FTP server: 192.168.49.245:1234
07-06 08:14:15.390 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 4096 bytes of 4081409866
07-06 08:14:15.397 26593-26900/cmc.com.httpclient E/UploadService: 4aa50051-069b-4f96-904c-e98f1dc1e0d1 now holds the foreground notification
07-06 08:14:15.553 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 1736704 bytes of 4081409866
07-06 08:14:15.719 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 4218880 bytes of 4081409866
07-06 08:14:15.885 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 6819840 bytes of 4081409866
07-06 08:14:16.051 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 9359360 bytes of 4081409866
07-06 08:14:16.217 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 11579392 bytes of 4081409866
07-06 08:14:16.383 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 13885440 bytes of 4081409866
07-06 08:14:16.549 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 16404480 bytes of 4081409866
07-06 08:14:16.715 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 18833408 bytes of 4081409866
07-06 08:14:16.881 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 21491712 bytes of 4081409866
07-06 08:14:17.047 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 24080384 bytes of 4081409866
07-06 08:14:17.213 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 26558464 bytes of 4081409866
07-06 08:14:17.379 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 29081600 bytes of 4081409866
07-06 08:14:17.545 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 31461376 bytes of 4081409866
07-06 08:14:17.711 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 34021376 bytes of 4081409866
07-06 08:14:17.877 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 36540416 bytes of 4081409866
07-06 08:14:18.043 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 39182336 bytes of 4081409866
07-06 08:14:18.209 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 41652224 bytes of 4081409866
07-06 08:14:18.375 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 44158976 bytes of 4081409866
07-06 08:14:18.541 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 46825472 bytes of 4081409866
07-06 08:14:18.707 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 49414144 bytes of 4081409866
07-06 08:14:18.873 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 52068352 bytes of 4081409866
07-06 08:14:19.039 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 54697984 bytes of 4081409866
07-06 08:14:19.205 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 57294848 bytes of 4081409866
07-06 08:14:19.371 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 60063744 bytes of 4081409866
07-06 08:14:19.537 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 62676992 bytes of 4081409866
07-06 08:14:19.710 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 65589248 bytes of 4081409866
07-06 08:14:19.895 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 69238784 bytes of 4081409866
07-06 08:14:20.061 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 71438336 bytes of 4081409866
07-06 08:14:20.227 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 74166272 bytes of 4081409866
07-06 08:14:20.393 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 76709888 bytes of 4081409866
07-06 08:14:20.562 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 79749120 bytes of 4081409866
07-06 08:14:20.727 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 82427904 bytes of 4081409866
07-06 08:14:20.895 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 86048768 bytes of 4081409866
07-06 08:14:21.061 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 88879104 bytes of 4081409866
07-06 08:14:21.227 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 91488256 bytes of 4081409866
07-06 08:14:21.393 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 93970432 bytes of 4081409866
07-06 08:14:21.559 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 96542720 bytes of 4081409866
07-06 08:14:21.725 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 99176448 bytes of 4081409866
07-06 08:14:21.891 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 101781504 bytes of 4081409866
07-06 08:14:22.057 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 104300544 bytes of 4081409866
07-06 08:14:22.223 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 106897408 bytes of 4081409866
07-06 08:14:22.391 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 110542848 bytes of 4081409866
07-06 08:14:22.557 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 112664576 bytes of 4081409866
07-06 08:14:22.723 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 115187712 bytes of 4081409866
07-06 08:14:22.889 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 117866496 bytes of 4081409866
07-06 08:14:23.055 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 120426496 bytes of 4081409866
07-06 08:14:23.221 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 123023360 bytes of 4081409866
07-06 08:14:23.387 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 125648896 bytes of 4081409866
07-06 08:14:23.553 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 128241664 bytes of 4081409866
07-06 08:14:23.723 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 131637248 bytes of 4081409866
07-06 08:14:24.023 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 133173248 bytes of 4081409866
07-06 08:14:24.188 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 135225344 bytes of 4081409866
07-06 08:14:24.354 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 137728000 bytes of 4081409866
07-06 08:14:24.520 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 140288000 bytes of 4081409866
07-06 08:14:24.686 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 142802944 bytes of 4081409866
07-06 08:14:24.852 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 145182720 bytes of 4081409866
07-06 08:14:25.018 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 147828736 bytes of 4081409866
07-06 08:14:25.190 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 150740992 bytes of 4081409866
07-06 08:14:25.356 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 152809472 bytes of 4081409866
07-06 08:14:25.522 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 155328512 bytes of 4081409866
07-06 08:14:25.688 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 157990912 bytes of 4081409866
07-06 08:14:25.854 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 160501760 bytes of 4081409866
07-06 08:14:26.020 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 162881536 bytes of 4081409866
07-06 08:14:26.186 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 165441536 bytes of 4081409866
07-06 08:14:26.352 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 167981056 bytes of 4081409866
07-06 08:14:26.518 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 170479616 bytes of 4081409866
07-06 08:14:26.684 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 173072384 bytes of 4081409866
07-06 08:14:26.850 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 175661056 bytes of 4081409866
07-06 08:14:27.016 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 178237440 bytes of 4081409866
07-06 08:14:27.182 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 180756480 bytes of 4081409866
07-06 08:14:27.348 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 183296000 bytes of 4081409866
07-06 08:14:27.514 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 185946112 bytes of 4081409866
07-06 08:14:27.680 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 188465152 bytes of 4081409866
07-06 08:14:27.846 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 190996480 bytes of 4081409866
07-06 08:14:28.012 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 193675264 bytes of 4081409866
07-06 08:14:28.178 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 196288512 bytes of 4081409866
07-06 08:14:28.344 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 198733824 bytes of 4081409866
07-06 08:14:28.510 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 201355264 bytes of 4081409866
07-06 08:14:28.676 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 203980800 bytes of 4081409866
07-06 08:14:28.842 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 206479360 bytes of 4081409866
07-06 08:14:29.008 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 209158144 bytes of 4081409866
07-06 08:14:29.174 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 211779584 bytes of 4081409866
07-06 08:14:29.340 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 214212608 bytes of 4081409866
07-06 08:14:29.506 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 216858624 bytes of 4081409866
07-06 08:14:29.672 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 219258880 bytes of 4081409866
07-06 08:14:29.838 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 221552640 bytes of 4081409866
07-06 08:14:30.004 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 223977472 bytes of 4081409866
07-06 08:14:30.170 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 226398208 bytes of 4081409866
07-06 08:14:30.340 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 229392384 bytes of 4081409866
07-06 08:14:45.402 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 230039552 bytes of 4081409866
07-06 08:15:00.428 26593-26900/cmc.com.httpclient E/UploadTask: Broadcasting upload progress for 4aa50051-069b-4f96-904c-e98f1dc1e0d1: 230043648 bytes of 4081409866

**Comment by shweps** [comment] 2017-07-06 12:18
i notice that it still sending data but very very slow

**Comment by shweps** [comment] 2017-07-06 14:11
also happened in galaxy A3 with marshmallow

**Comment by gotev** [comment] 2017-07-06 14:18
It can be due to [Doze mode](https://github.com/gotev/android-upload-service/issues/227#issuecomment-274263516)

**Comment by shweps** [comment] 2017-07-06 14:44
i disable the doze mode and it still happened... have another idea? its slow down almost stop after 15 seconds

**Comment by gotev** [comment] 2017-07-06 16:24
it could be many things. Isolating the problem is crucial. These are some tests which I thought of:
* upload the same files from a mac or pc using filezilla or other ftp client.
* try upload from a virtual device running Android 6+
* try upload from a real device with Android < 5.0
* try upload with the device screen constantly on.

For each one of these test cases, you should check if you have the same behaviour you described, so we can at least know if the problem is specific to Apache Commons FTP, the backgrouding on Android or some bandwidth limitations on your server-side.

**Comment by shweps** [comment] 2017-07-09 07:09
Hi Alex Gotev, first of all thank you for the response.
i have tried all of the above and dose are my results:
- upload the same files from a mac or pc using filezilla or other ftp client: 
               works fine not as fast but good from end to end.
- try upload from a virtual device running Android 6+: 
               i didnt test this part.
- try upload from a real device with Android < 5.0:
               i have tried to use my on client build on the Apache Commons FTP and it works fine
               the code i use is :  
               public boolean ftpDownload(FTPFile serverFile) {
                          String path = new File(Environment.getExternalStorageDirectory().getAbsolutePath(), 
                                                "Movies").getAbsolutePath();
                          File file = new File (path, serverFile.getName());
                          if (file.exists ()) file.delete ();
                                   FileOutputStream fileOutputStream = null;
                                   try {
                                            fileOutputStream = new FileOutputStream(file);
                                            long startTime = System.currentTimeMillis();
                                            boolean success = mFTPClient.retrieveFile(file.getName(), fileOutputStream);
                                            long endTime = System.currentTimeMillis();
                                            Log.i("TEST", "total time for \"" + file.getName() + "\": " + (endTime 
                                                     startTime));
                                            return mFTPClient.completePendingCommand();
                                      } catch (Exception e) {
                                            e.printStackTrace();
                                      } finally {
                                                    try {
                                                              fileOutputStream.close();
                                                    } catch (IOException e) {
                                                              e.printStackTrace();
                                             }
                                 }
                            return false;
                         }

                 and on lg g6 to lg g5 both android api 6+ and it still works fine. still mutch slower then your's.
- try upload with the device screen constantly on.
           still dose not help.

**Comment by gotev** [comment] 2017-07-09 07:43
The Apache FTP code you posted is for download, not upload, so that test can't be considered. Downloading and uploading are two different things. Different parts of the FTP library are involved. Regarding the first test, tell me the length of the transferred files.

**Comment by shweps** [comment] 2017-07-09 07:48
public synchronized boolean ftpUpload(String srcFilePath, String desFileName) {
        boolean status = false;
        try {
            FileInputStream fileInputStream = new FileInputStream(srcFilePath);
            mFTPClient.setBufferSize(1024 * 1024);
            ProgressInputStream progressInput = new ProgressInputStream(fileInputStream.getChannel().size(),
                    fileInputStream, this);
            status = mFTPClient.storeFile(desFileName, progressInput);
            fileInputStream.close();
            return status;
        } catch (Exception e) {
            e.printStackTrace();
            Log.d(TAG, "upload failed: " + e);
        }
        return status;
    }
my mistake i have tried both

**Comment by shweps** [comment] 2017-07-09 07:49
and the file is 3.8GB movie.mp4

**Comment by gotev** [comment] 2017-07-09 08:23
A part from all the configuration options which the FTP module has, the only differences I could spot in the way the upload is done are:
*  you are monitoring the progress with `ProgressInputStream`, which is a class I could not find in the FTP commons library. The FTP module uses the [CopyStreamListener](https://commons.apache.org/proper/commons-net/apidocs/org/apache/commons/net/io/CopyStreamListener.html). 
* you use a buffer of 1MB, where the default buffer used by Upload Service is 4KB. You can customize it by calling `UploadService.BUFFER_SIZE = 1024 * 1024;` in the application initializer

Also, I've seen there's a newer [3.6](https://commons.apache.org/proper/commons-net/changes-report.html#a3.6) version of the  commons net library in which they've fixed many things, so I'll schedule an update for the next release. Have you used that version for your tests?

Also, another thing I spotted only now by looking at your [debug log](https://github.com/gotev/android-upload-service/issues/287#issuecomment-313379184) is that you are making two FTP requests for two files, where you can simply have a single FTP request with many files, which is a lot more efficient

**Comment by shweps** [comment] 2017-07-09 08:43
yes i used 3.6 version in my code also ProgressInputStream is wrapper that is made to follow the progress.
i change to UploadService.BUFFER_SIZE = 1024 * 1024 still didnt help

**Comment by gotev** [comment] 2017-07-09 09:12
@shweps just published new upload service 3.6. Try it and let me know if something changes

**Comment by shweps** [comment] 2017-07-09 10:39
so i finaly found the issue i needed to set .setSocketTimeout(1000000) because i guess that the default is 15s and the socket turn down after that. still the uplode is slow dou

**Comment by gotev** [comment] 2017-07-10 05:54
@shweps so it seems your server-side FTP does not have keep alive enabled. If you want to disable socket timeout on the client, just pass 0 in the FTP config. If you have control over your FTP, I definitely recommend you to have keep alive enabled on the client with the socket timeout and setup keep alive on the server. [Example for ProFTPd](http://www.proftpd.org/docs/howto/KeepAlives.html)

**Closed by gotev** 2017-07-10 05:54 UTC
