### ISSUE TITLE
Modify the notification from task callbacks

### ISSUE THREAD

**Issue by gotev** [gotev/android-upload-service#260] opened 2017-04-01 10:30 UTC
It will be useful to be able to modify each task's notification from its callbacks

**Comment by akiller** [comment] 2017-05-19 11:33
Just a very quick thought but for this and #259 would there be any benefit in passing a delegate into BinaryUploadRequest which is responsible for determining the upload result? This could be called during both completed and errored requests to allow the app to override the actual result of the upload and resulting notification of the upload.

We have a service that returns a 200 response code but returns a JSON error object in the response text - would it not make sense to optionally allow each app to tell you (the upload service) how to deal with it? E.g., if our service returns an error code that the uploaded file is a duplicate of one that already exists we may want to just gracefully accept it on the app rather than show an error.

For example:

```
public class RequestResultParser {
    public boolean isSuccessful(UploadInfo uploadInfo, ServerResponse serverResponse) {
        if (serverResponse.getHttpCode() != HttpStatus.SC_OK)
            return false;

        // We could deserialise the JSON and do checks based on error code etc here
        if (serverResponse.getBodyAsString().contains("{error:"))
            return false;

        return true;
    }
}
```

**Comment by gotev** [comment] 2017-05-23 20:55
Ideally, what I want to achieve is to pass the notification itself to the onSuccess and onError callbacks. At that point you could modify it as you wish. You can add all the required business logic in the onSuccess and onFailure callbacks to best accomodate your needs and to override the default behaviour.

> We have a service that returns a 200 response code but returns a JSON error object in the response text

I advise you to return a 4xx from your server if the upload is not successful or some server-side validation does not pass, as I wrote [here](https://github.com/gotev/android-upload-service/issues/259#issuecomment-290774828) to be as standard compliant as possible.

**Comment by akiller** [comment] 2017-05-23 21:35
> Ideally, what I want to achieve is to pass the notification itself to the onSuccess and onError callbacks. At that point you could modify it as you wish. You can add all the required business logic in the onSuccess and onFailure callbacks to best accomodate your needs and to override the default behaviour.

Oh OK, that makes sense to me. It sounds pretty simple in theory but I'm sure it won't be!

>I advise you to return a 4xx from your server if the upload is not successful or some server-side validation does not pass, as I wrote here to be as standard compliant as possible.

Definitely. It wasn't my doing :). We're currently using our own uploader for most of our apps but are considering moving them over to this library and will update to proper status codes at that point.

**Comment by PhilLab** [comment] 2017-06-21 12:24
Is there a broadcasting/intent possibility to remove the "upload successful" notification after some time?

I upload files to the server, then change the success message to "please wait for the server to process your uploads" and after some time the server notifies me about the processing being finished. In this moment, I want to remove the AndroidUploadService notification

**Comment by gotev** [comment] 2017-07-27 04:38
@PhilLab currently there's no such feature, butwhat you propose is interesting

**Comment by gotev** [comment] 2017-07-28 14:13
Thinking of a way to pass the entire `Notification.Builder` to the broadcast receivers, to be able to modify the notification from the callbacks there are the following problems:
* everything which is transmitted in a broadcast intent must be `Parcelable` or at least `Serializable`. `NotificationCompat.Builder` is not.
* If I invoke the `build` method on the builder, I get a parcelable notification, but I couldn't modify it
* Even if I find some way of passing the editable notification to the callbacks, there's another problem. The task communicates in a decoupled way with the receiver, so If I send an event, I have to wait for another event to come in to proceed. In this case, when I send the notification, I have to wait for another incoming intent to be able to proceed to display the notification. This smells of bad design.
* Considering only callbacks instead of broadcast receivers, the problems listed above are gone, but as I wrote in #292 the actual callbacks implementation leads to memory leaks in many cases.

So, after those thoughts, I think there is no way of passing the notification to the callbacks, modify them inside the callbacks, return them to the task and then display them in the notification center. I'm open to further ideas. If nothing comes in, I'll mark this as `wontfix` in a month from now

**Closed** 2017-11-19 17:55 UTC
Labels: wontfix
