### ISSUE TITLE
Problem in uploading image 

### ISSUE THREAD

**Issue by priyochatterjee08** [gotev/android-upload-service#70] opened 2016-01-05 18:07 UTC
01-05 23:35:31.945 30439-30439/in.futuretrucks E/AndroidUploadService: Error in upload with ID: 61e734e8-704b-4e8f-859e-b7bf1c4a021c. sendto failed: EPIPE (Broken pipe)
                                                                       java.net.SocketException: sendto failed: EPIPE (Broken pipe)
                                                                           at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:586)
                                                                           at libcore.io.IoBridge.sendto(IoBridge.java:555)
                                                                           at java.net.PlainSocketImpl.write(PlainSocketImpl.java:513)
                                                                           at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:42)
                                                                           at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:271)
                                                                           at com.android.okio.Okio$1.write(Okio.java:70)
                                                                           at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116)
                                                                           at com.android.okio.RealBufferedSink.write(RealBufferedSink.java:44)
                                                                           at com.android.okhttp.internal.http.HttpConnection$FixedLengthSink.write(HttpConnection.java:287)
                                                                           at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116)
                                                                           at com.android.okio.RealBufferedSink$1.write(RealBufferedSink.java:131)
                                                                           at com.alexbbb.uploadservice.HttpUploadTask.writeStream(HttpUploadTask.java:240)
                                                                           at com.alexbbb.uploadservice.MultipartUploadTask.writeFiles(MultipartUploadTask.java:137)
                                                                           at com.alexbbb.uploadservice.MultipartUploadTask.writeBody(MultipartUploadTask.java:107)
                                                                           at com.alexbbb.uploadservice.HttpUploadTask.upload(HttpUploadTask.java:131)
                                                                           at com.alexbbb.uploadservice.MultipartUploadTask.upload(MultipartUploadTask.java:41)
                                                                           at com.alexbbb.uploadservice.HttpUploadTask.run(HttpUploadTask.java:65)
                                                                           at com.alexbbb.uploadservice.UploadService.onHandleIntent(UploadService.java:127)
                                                                           at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                           at android.os.Looper.loop(Looper.java:194)
                                                                           at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                        Caused by: android.system.ErrnoException: sendto failed: EPIPE (Broken pipe)
                                                                           at libcore.io.Posix.sendtoBytes(Native Method)
                                                                           at libcore.io.Posix.sendto(Posix.java:176)
                                                                           at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
                                                                           at libcore.io.IoBridge.sendto(IoBridge.java:553)
                                                                           at java.net.PlainSocketImpl.write(PlainSocketImpl.java:513) 
                                                                           at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:42) 
                                                                           at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:271) 
                                                                           at com.android.okio.Okio$1.write(Okio.java:70) 
                                                                           at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116) 
                                                                           at com.android.okio.RealBufferedSink.write(RealBufferedSink.java:44) 
                                                                           at com.android.okhttp.internal.http.HttpConnection$FixedLengthSink.write(HttpConnection.java:287) 
                                                                           at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116) 
                                                                           at com.android.okio.RealBufferedSink$1.write(RealBufferedSink.java:131) 
                                                                           at com.alexbbb.uploadservice.HttpUploadTask.writeStream(HttpUploadTask.java:240) 
                                                                           at com.alexbbb.uploadservice.MultipartUploadTask.writeFiles(MultipartUploadTask.java:137) 
                                                                           at com.alexbbb.uploadservice.MultipartUploadTask.writeBody(MultipartUploadTask.java:107) 
                                                                           at com.alexbbb.uploadservice.HttpUploadTask.upload(HttpUploadTask.java:131) 
                                                                           at com.alexbbb.uploadservice.MultipartUploadTask.upload(MultipartUploadTask.java:41) 
                                                                           at com.alexbbb.uploadservice.HttpUploadTask.run(HttpUploadTask.java:65) 
                                                                           at com.alexbbb.uploadservice.UploadService.onHandleIntent(UploadService.java:127) 
                                                                           at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                           at android.os.Looper.loop(Looper.java:194) 
                                                                           at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by alexbbb** [comment] 2016-01-07 11:24
Please check this: https://github.com/alexbbb/android-upload-service#before-asking-for-help
If you use PHP for your server side, you generally have this behaviour when the data you want to upload exceeds  the values of `upload_max_filesize` or `post_max_size` set in `php.ini`.

**Comment by priyochatterjee08** [comment] 2016-01-08 08:58
this is what I have done:

  public void uploadMultipart(final Context context , String path) {
        Log.e("ComeON","Upload multipart 1");

        final String uploadID = UUID.randomUUID().toString();
        String jwt = PreferenceClass.getStringPreferences(appContext, Constant.USER_TOKEN);
        String user_id = PreferenceClass.getStringPreferences(appContext, Constant.USER_ID);
        final String serverUrlString = "";
        Log.e("ComeON","Upload multipart 2");
        try {
            new MultipartUploadRequest(context, uploadID, serverUrlString)
                    .addHeader("Authorization", "JWT "+jwt)
                    .addFileToUpload(path, "profile_img","test","multipart/form")
                    .setMethod("PUT")
                    .setNotificationConfig(new UploadNotificationConfig())
                    .setMaxRetries(2)
                    .startUpload();
            Log.e("ComeON", "Upload multipart 3");
        } catch (Exception exc) {
            Log.e("AndroidUploadService", exc.getMessage(), exc);
        }
    }
    private final UploadServiceBroadcastReceiver uploadReceiver =
            new UploadServiceBroadcastReceiver() {

                // you can override this progress method if you want to get
                // the completion progress in percent (0 to 100)
                // or if you need to know exactly how many bytes have been transferred
                // override the method below this one
                @Override
                public void onProgress(String uploadId, int progress) {
                    Log.i(TAG, "The progress of the upload with ID "
                            + uploadId + " is: " + progress);
                }

                @Override
                public void onProgress(final String uploadId,
                                       final long uploadedBytes,
                                       final long totalBytes) {
                    Log.i(TAG, "Upload with ID " + uploadId +
                            " uploaded bytes: " + uploadedBytes
                            + ", total: " + totalBytes);
                }

                @Override
                public void onError(String uploadId, Exception exception) {
                    Log.e(TAG, "Error in upload with ID: " + uploadId + ". "
                            + exception.getLocalizedMessage(), exception);
                }

                @Override
                public void onCompleted(String uploadId,
                                        int serverResponseCode,
                                        String serverResponseMessage) {
                    Log.i(TAG, "Upload with ID " + uploadId
                            + " has been completed with HTTP " + serverResponseCode
                            + ". Response from server: " + serverResponseMessage);


                    //If your server responds with a JSON, you can parse it
                    //from serverResponseMessage string using a library
                    //such as org.json (embedded in Android) or Google's gson
                }
            };

**Comment by alexbbb** [comment] 2016-01-08 10:07
The code you posted is ok, except this statement:
```java
.addFileToUpload(path, "profile_img","test","multipart/form")
```
because `multipart/form` is not a valid content type for a file. Check the [addFileToUpload method JavaDoc](http://alexbbb.github.io/android-upload-service/javadoc/com/alexbbb/uploadservice/MultipartUploadRequest.html#addFileToUpload-java.lang.String-java.lang.String-java.lang.String-java.lang.String-).

After fixing that, check your server-side, because I think the problem is there. From the stack trace you posted, you can see that the error originated [here](https://github.com/alexbbb/android-upload-service/blob/master/uploadservice/src/main/java/com/alexbbb/uploadservice/HttpUploadTask.java#L240):
```
com.alexbbb.uploadservice.HttpUploadTask.writeStream(HttpUploadTask.java:240)
```
This happens when the server closes the connection before the request is completed, and so you get that exception. I suggest you to checkout the project sources and try the [node.js server example](https://github.com/alexbbb/android-upload-service#examples-) with your android app. You can get it up and running in a matter of minutes. Let me know if the same exception occurs by using the demo server.

**Comment by alexbbb** [comment] 2016-01-13 13:05
@priyochatterjee08 have you tries the demo server or resolved your server side issue?

**Comment by priyochatterjee08** [comment] 2016-01-13 13:19
How do I know the content type in advance like whether it would be jpeg or png or pdf? My server is fine because I can upload the file through retrofit.

**Comment by alexbbb** [comment] 2016-01-13 13:24
Do not explicitly set it, by passing null, or use Java 7's
Files.probeContentType(path).
Il 13 gen 2016 2:19 PM, "Priyabrata Chatterjee" <notifications@github.com>
ha scritto:

**Comment by alexbbb** [comment] 2016-01-13 21:12
@priyochatterjee08 could you please post an example of how you do the upload with retrofit and with which version? I'm going to try that out with my server and dump the request to see what's the difference. Maybe I'm doing something wrong in the multipart request. Your question about the content type setting made me look in detail in the code, and I've found that actually in release 1.6 if you don't explicitly set the content type (by passing `null`), `application/octet-stream` is used by default. I've improved that in #77 and it will be included in the 2.0 release.

**Comment by priyochatterjee08** [comment] 2016-01-14 07:14
File Upload Service

public interface FileUploadService {
    @Multipart
    @PUT("/api/users/{user_id}")
    Call<UploadFileApiResponse> upload(
            @Path("user_id") String user_id,
            @Header("Authorization") String authorization,
            @Part("profile_img\"; filename=\"image.jpg\" ") RequestBody file);

}

Call from Activity Class:

      FileUploadService service =
                            ServiceGenerator.createService(FileUploadService.class);

                    File file = new File(profile_pic_path);
                    String mimeType = getMimeType(profile_pic_path);
                    RequestBody requestBody =
                            RequestBody.create(MediaType.parse(mimeType), file);
                    String jwt = PreferenceClass.getStringPreferences(appContext,Constant.USER_TOKEN);
                    String user_id = PreferenceClass.getStringPreferences(appContext,Constant.USER_ID);

                    Call<UploadFileApiResponse> call = service.upload(user_id, jwt, requestBody);
                    call.enqueue(new Callback<UploadFileApiResponse>() {
                        @Override
                        public void onResponse(Response<UploadFileApiResponse> response, Retrofit retrofit) {
                            Toast.makeText(appContext, R.string.not_Profile_Image, Toast.LENGTH_LONG).show();
                        }

                        @Override
                        public void onFailure(Throwable t) {

                        }
                    });
                   

Service Generator.java

public class ServiceGenerator {

    public static final String API_BASE_URL = "http://abcd.in:3000/";

    private static OkHttpClient httpClient = new OkHttpClient();

    private static Retrofit.Builder builder =
            new Retrofit.Builder()
                    .baseUrl(API_BASE_URL)
                    .addConverterFactory(GsonConverterFactory.create());

    public static <S> S createService(Class<S> serviceClass) {

        if (serviceClass == ZApiService.class || serviceClass == ZZApiService.class) {

            Log.e("debug",serviceClass.toString());
            httpClient.interceptors().add(new Interceptor() {
                @Override
                public Response intercept(Interceptor.Chain chain) throws IOException {
                    Request original = chain.request();

                    Request.Builder requestBuilder = original.newBuilder()
                            .header("cache-control", "no-cache")
                            .method(original.method(), original.body());

                    Request request = requestBuilder.build();
                    return chain.proceed(request);
                }
            });
        }
        else {
            httpClient.interceptors().add(new Interceptor() {
                @Override
                public Response intercept(Interceptor.Chain chain) throws IOException {
                    Request original = chain.request();

                    Request.Builder requestBuilder = original.newBuilder()
                            .header("Content-Type", "multipart/form-data")
                            .header("cache-control","no-cache")
                            .method(original.method(), original.body());

                    Request request = requestBuilder.build();
                    return chain.proceed(request);
                }
            });
        }
        HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();
        interceptor.setLevel(HttpLoggingInterceptor.Level.BODY);
        httpClient.interceptors().add(interceptor);

        Retrofit retrofit = builder.client(httpClient).build();
        return retrofit.create(serviceClass);
    }


}

**Comment by alexbbb** [comment] 2016-01-19 23:25
Thank you. I will try it as soon as I can. Made some improvements in connection setup in the new 2.0, which I've just released. If you want you can try it out.

**Comment by gotev** [comment] 2016-02-12 17:34
The problem is not reproducible anymore with release 2.0.1, so I'm closing this ticket. Open a new one if you have issues.

**Closed by gotev** 2016-02-12 17:34 UTC
Labels: support
