### ISSUE TITLE
Can't upload file to server?

### ISSUE THREAD

**Issue by vanloc0301** [gotev/android-upload-service#119] opened 2016-04-25 07:17 UTC
Before time, I can upload file to server perfect.
But current I have 141 file in local android storage and want upload all to server.

I have error like:

```java
Error in uploadId 333bbf86-d2ef-45d1-8ed4-c3fdf47fdfe9 on attempt 1. Waiting 1s before next attempt
    java.net.ProtocolException: unexpected end of stream
    at com.android.okhttp.internal.http.HttpTransport$FixedLengthOutputStream.close(HttpTransport.java:253)
    at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:636)
    at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
    at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
    at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
    at net.gotev.uploadservice.HttpUploadTask.upload(HttpUploadTask.java:169)
    at net.gotev.uploadservice.HttpUploadTask.run(HttpUploadTask.java:113)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:864) 
```

It create 141 log like this:

> getaddrinfo+,hn 25(0x76696574706861),sn(),family 0,flags 4
> getaddrinfo-,err=8
> getaddrinfo+,hn 25(0x76696574706861),sn(),family 0,flags 1024
> getaddrinfo-, 1
> getaddrinfo_proxy+
> getaddrinfo_proxy-, success

It show `success and err=8`. I don't know this error or success.

Here my code:

```java
pathRootLapsoft = new File(Environment.getExternalStorageDirectory().getAbsolutePath() + "/Lapsoft-CRM/");
fileListWasAdded = getFileFromDirectory(pathRootLapsoft);

if(fileListWasAdded.isEmpty())
  listView.setAdapter(null);

for(File filePathName : fileListWasAdded)
try {
  try {
    Thread.sleep(200);                 //200 milliseconds is one second.
  } catch(InterruptedException ex) {
    Thread.currentThread().interrupt();
  }
  String filename = getFilename(filePathName.getPath()).replaceAll("\\s+","_");


  MultipartUploadRequest req = new MultipartUploadRequest(this, serverUrlString)
      .addFileToUpload(filePathName.getPath().replaceAll("\\s+","_"), paramNameString)
                .setCustomUserAgent(USER_AGENT)
      .setAutoDeleteFilesAfterSuccessfulUpload(false)
                .setUsesFixedLengthStreamingMode(true)
      .setMaxRetries(2);
  String uploadID = req.startUpload();
  if(uploadID != null) {

  }
}
```

**Comment by gotev** [comment] 2016-04-25 08:20
Which Http Stack are you using with Android Upload Service and on which Android version does this happen?  Are your uploads successful at the end? By what I see from your report, it seems that something happened on your device network connection during the first upload attempt because you may have `java.net.ProtocolException: unexpected end of stream` it usually means a network error between your device and your server. How is the device connected to your server when this happens? WiFi or Mobile (Edge, 3G, 4G)?

**Comment by vanloc0301** [comment] 2016-04-25 08:27
My phone using Wifi.

I upload array file but don't have any file in server.

I try with code to upload only a file:

```
final String paramNameString = "uploaded_file";

final String pathCurrentFileName = recorder.getFileName();
final String filesToUploadString = getFilename(pathCurrentFileName.toString().replaceAll("\\s+", "_"));

try {
	MultipartUploadRequest stun = new MultipartUploadRequest(this, serverUrlString)
			.addFileToUpload(pathCurrentFileName.replaceAll("\\s+","_"), paramNameString)
			.setCustomUserAgent(USER_AGENT)
			.setAutoDeleteFilesAfterSuccessfulUpload(false)
			.setUsesFixedLengthStreamingMode(true)
			.setMaxRetries(2);
	String uploadCurrentFile = stun.startUpload();
	if (uploadCurrentFile != null) {

	}
	dao.deleteCallWhenUploadSuccess(filesToUploadString);
} catch (MalformedURLException exc) {
	showToast(exc.getMessage());
} catch (FileNotFoundException e) {
	e.printStackTrace();
}
```


But I go to upload multiple files, the exception occurs.
Before, I am working(in current my device tested).

**Comment by gotev** [comment] 2016-04-25 08:54
Ok, so from what you say one request is sucessful, but when you make 141 requests, you get that error. I need to know:
* on which Android version does this happen, 
* with which Http Stack (`HurlStack` or `OkHttpStack`)
* with which Android Upload Service version

Enable also library debug log, as described [here](https://github.com/gotev/android-upload-service/wiki/Recipes#logging-) and post what you get when you perform the requests which throws the Exceptions. When posting code, logs or stack traces, please always the following Markdown syntax to improve readability:
<pre>
```
your code, log or stack trace
```
</pre>
Thank you :)

**Comment by vanloc0301** [comment] 2016-04-25 09:09
This is all information:

- Android 4.4.4 API 19.
- Http Stack? I don't know about this. I only using your library and try to upload a file to the server.
- Android Upload Service version: net.gotev:uploadservice: 2.0.1 not net.gotev:uploadservice:okhttp 2.1.

I trying update to `uploadservice:2.1` and using `Logger.setLogLevel(LogLevel.DEBUG);` to using Log.
Waiting for minutes. Thanks.

**Comment by vanloc0301** [comment] 2016-04-25 09:59
I change my code to:


```
public void MultipartUploadFileAudioRecord(final Context context) {
	final String serverUrlString = "http://" + serverURL + "/main.php?nm=appandroid&app_id=android";
	final String paramNameString = "uploaded_file";

	pathRootLapsoft = new File(Environment.getExternalStorageDirectory().getAbsolutePath() + "/GoLink-CRM/");
	fileListWasAdded = getFileFromDirectory(pathRootLapsoft);


	if(fileListWasAdded.isEmpty())
		listView.setAdapter(null);

	for(File filePathName : fileListWasAdded)
	try {
		try {
			Thread.sleep(200);                 //200 milliseconds is one second.
		} catch(InterruptedException ex) {
			Thread.currentThread().interrupt();
		}
		String filename = getFilename(filePathName.getPath()).replaceAll("\\s+","_");
		String uploadId =
				new MultipartUploadRequest(context, serverUrlString)
						.addFileToUpload(filePathName.getPath().replaceAll("\\s+", "_"), paramNameString)
						.setNotificationConfig(new UploadNotificationConfig())
						.setMaxRetries(2)
						.startUpload();
		dao.deleteCallWhenUploadSuccess(filename);
	} catch (Exception exc) {
		Log.e("AndroidUploadService", exc.getMessage(), exc);
	}
}
```

It has an error like:

`A/PowerManager: WakeLock finalized while still held: UploadService`

It doesn't throw exception, and you can see this is all log in the `logcat`:


```

D/UploadService: HttpUploadRequest - null or empty upload ID. Generating it
D/UploadService: HttpUploadRequest - Created new upload request to http://example.net/main.php?nm=appandroid&app_id=android&uid=android with ID: a1afcdf6-4372-4fd5-9b84-590fdbafc4c3
D/UploadService: UploadFile - Detected MIME type for /storage/emulated/0/GoLink-CRM/01643653367_2016-04-22_09.11.51.mp4 is: null
D/UploadService: UploadFile - Using original file name: null
I/UploadService: UploadService - Starting service with namespace: net.gotev.uploadservice, upload pool size: 4, 1s idle thread keep alive time. Foreground execution is enabled
D/UploadService: UploadService - Successfully created new task with class: net.gotev.uploadservice.MultipartUploadTask
D/UploadService: UploadService - a1afcdf6-4372-4fd5-9b84-590fdbafc4c3 now holds the foreground notification
D/UploadService: HttpUploadTask - Starting upload task with ID a1afcdf6-4372-4fd5-9b84-590fdbafc4c3
D/UploadService: HurlStackConnection - creating new connection
D/libc: [NET] getaddrinfo+,hn 25(0x76696574706861),sn(),family 0,flags 4
D/libc: [NET] getaddrinfo-,err=8
D/libc: [NET] getaddrinfo+,hn 25(0x76696574706861),sn(),family 0,flags 1024
D/libc: [NET] getaddrinfo-, 1
D/libc: [NET] getaddrinfo_proxy+
D/libc: [NET] getaddrinfo_proxy-, success

D/UploadService: HurlStackConnection - closing connection
I/UploadService: HttpUploadTask - Error in uploadId 9c719e03-63f2-4a88-a207-8280849afdf2 on attempt 1. Waiting 1s before next attempt. unexpected end of stream
D/UploadService: HttpUploadTask - Server responded with HTTP 200 to upload with ID: a1afcdf6-4372-4fd5-9b84-590fdbafc4c3
D/UploadService: HttpUploadTask - Broadcasting upload completed for a1afcdf6-4372-4fd5-9b84-590fdbafc4c3
D/RingtoneManager: getActualDefaultRingtoneUri(context, 2)
D/UploadService: UploadService - a1afcdf6-4372-4fd5-9b84-590fdbafc4c3 now un-holded the foreground notification
D/UploadService: HurlStackConnection - closing connection
D/libc: [NET] getaddrinfo+,hn 29(0x7777772e766965),sn(),family 0,flags 4
D/libc: [NET] getaddrinfo-,err=8
D/libc: [NET] getaddrinfo+,hn 29(0x7777772e766965),sn(),family 0,flags 1024
D/libc: [NET] getaddrinfo-, 1
D/libc: [NET] getaddrinfo_proxy+
D/libc: [NET] getaddrinfo_proxy-, success
```

**Comment by gotev** [comment] 2016-04-25 10:13
Thank you for the detailed report :+1: 
At this point, it will be useful to test your code against Android Upload Service demo server, to see if the exact same error happens, so I can replicate it too. To make this test, start the node.js demo server on your computer, by following [this guide](https://github.com/gotev/android-upload-service/wiki/Testing%20and%20working%20examples). It won't take you more than 5 minutes if you need to also install node.js. When started, the node.js demo server will show you the full URLs on which it listens for incoming connections. Just modify this line in your code:
```java
final String serverUrlString = "http://" + serverURL + "/main.php?nm=appandroid&app_id=android";
```
with:
```java
final String serverUrlString = "http://" + YOUR_COMPUTER_IP + ":3000/upload/multipart";
```
then run your app and post here what you get in the LogCat.

**Comment by gotev** [comment] 2016-04-25 10:37
Also, by analyzing your stack trace, I've noted this.
```java
D/UploadService: UploadFile - Using original file name: null
```
which I think is because you are doing:
```java
.addFileToUpload(filePathName.getPath().replaceAll("\\s+", "_"), paramNameString)
```
This way if you have a file which has spaces in it, you are substituting them with `_` and so when the Upload Service tries to read the file from disk, it fails. Just use `filePathName.getAbsolutePath()` here.

**Comment by vanloc0301** [comment] 2016-04-25 14:06
Tomorrow, I will test on my local server.

I will update my question.
Thank you very much. You are awesome.

**Comment by vanloc0301** [comment] 2016-04-26 05:24
Thanks pro.

I remove this line:
`replaceAll("\\s+", "_") and this working.
I also have problem when try delete file after upload success.

I tried with code:

```
public void MultipartUploadFileAudioRecord() {
	final String serverUrlString = "http://" + serverURL + "/main.php?nm=appandroid&uid=android";
	final String paramNameString = "uploaded_file";

	pathRootLapsoft = new File(Environment.getExternalStorageDirectory().getAbsolutePath() + "/Lapsoft-CRM/");
	fileListWasAdded = getFileFromDirectory(pathRootLapsoft);


	if(fileListWasAdded.isEmpty())
		listView.setAdapter(null);

	for(File filePathName : fileListWasAdded)
	try {
		try {
			Thread.sleep(200);                 //1000 milliseconds is one second.
		} catch(InterruptedException ex) {
			Thread.currentThread().interrupt();
		}
		String filename = getFilename(filePathName.getPath()).replaceAll("\\s+","_");
		MultipartUploadRequest uploadRequest  = new MultipartUploadRequest(this, serverUrlString)
						.addFileToUpload(filePathName.getAbsolutePath(), paramNameString)
						.setMaxRetries(2);
		String uploadCurrentFile = uploadRequest.startUpload();
		if (uploadCurrentFile != null && sendToServer()) {
			uploadRequest.setAutoDeleteFilesAfterSuccessfulUpload(true);
		}
		else uploadRequest.setAutoDeleteFilesAfterSuccessfulUpload(false);
      } catch (Exception exc) {
		Log.e("AndroidUploadService", exc.getMessage(), exc);
	}
}
```

I checked `sendToServer return values = true`.

I don't know class `setAutoDeleteFilesAfterSuccessfulUpload` working after I uploaded?


```
public String getTextFromInputStream(InputStream is) {
	BufferedReader reader = new BufferedReader(new InputStreamReader(is));
	StringBuilder stringBuilder = new StringBuilder();

	String currentLine;
	try {
		while ((currentLine = reader.readLine()) != null) {
			stringBuilder.append(currentLine);
			stringBuilder.append("\n");
		}
	} catch (IOException e) {
		e.printStackTrace();
	}

	return stringBuilder.toString().trim();
}

public boolean sendToServer() throws IOException {
	final String scripturlstring = "http://" + serverURL + "/main.php?nm=loc_demo&tp=0&cmd=cmd2&app_id=android&uid=android";
	URL scripturl = new URL(scripturlstring);
	HttpURLConnection connection = (HttpURLConnection) scripturl.openConnection();

	InputStream answerInputStream = connection.getInputStream();
	final String answer = getTextFromInputStream(answerInputStream);

	if (answer.equals("deleted")) return true;
	else return false;
}
```

**Comment by gotev** [comment] 2016-04-26 05:54
I'm glad to know that it's not a bug in the library :) I've seen also the code you posted, and I suggest you to read the Wiki, because this is wrong;
```java
        String uploadCurrentFile = uploadRequest.startUpload();
        if (uploadCurrentFile != null && sendToServer()) {
            uploadRequest.setAutoDeleteFilesAfterSuccessfulUpload(true);
        }
        else uploadRequest.setAutoDeleteFilesAfterSuccessfulUpload(false);
```
You are starting the upload request, and then you are setting `setAutoDeleteFilesAfterSuccessfulUpload` afterwards, so in this case, [as the docs says](http://gotev.github.io/android-upload-service/javadoc/net/gotev/uploadservice/MultipartUploadRequest.html#setAutoDeleteFilesAfterSuccessfulUpload-boolean-), no file is going to be deleted automatically. Remember that the request objects follows the Builder logic, so `startUpload` must be the last method you call on the request object. Every other method you call on that object after you called `startUpload` is not going to have any effect.
Check out the demo Android project that you can find in the examples. I'm closing this issue as the tracker here is used only for bug report and library development. This is much more of a support request at this point, and the right place to ask is on StackOverflow :)

**Closed by gotev** 2016-04-26 05:54 UTC

**Comment by vanloc0301** [comment] 2016-04-26 06:15
Thanks, @gotev . I using `filePathName.delete();` and this working.

**Comment by gotev** [comment] 2016-04-26 06:26
@vanloc0301 just one more thing...I suggest you to call your business logic methods from the `onCompleted` method of the `UploadServiceBroadcastReceiver` and not like you've shown in your post. The `onCompleted` method is the only place in which you know that the upload succeeded.
